### ISSUE TITLE
7.0.0 is not working on Windows

### ISSUE THREAD

**Issue by rtarnaud** [itgalaxy/favicons#403]
...as opposed to 7.0.0-beta.4 for example, which does work on Windows.

**Comment by andy128k** [comment]
Any details?

**Comment by hahnbeelee** [comment]
I'm testing on mac and it isn't working for me either. No errors are being thrown but my favicons are just not being generated.

**Comment by andy128k** [comment]
May you provide more details? How do you test? May it happen that you use a callback to get a result? Callbacks are not supported anymore (since beta.5).

`favicons(source, options, (error, result) => { ... })` should be changed to `favicons(source, options).then(result => { ... }, error => { ... })`.

**Comment by rtarnaud** [comment]
No I didn't update my code to reflect the switch to promises so I guess that's the issue. Thanks for the heads up but I would humbly suggest that you announce these kind of changes in a changelog document, not only in the readme. Especially when you change the API itself between a beta version and the corresponding release.

**Comment by hahnbeelee** [comment]
The change also isn't reflected on the [npm readme](https://www.npmjs.com/package/favicons)
