### ISSUE TITLE
`icons.<platform>.sizes` weird behaviour

### ISSUE THREAD

**Issue by MrFoxPro** [itgalaxy/favicons#434]
```js
icons: {
  android: {
     rotate: false,
     transparent: true,
     sizes: [{ width: 48, height: 48 }],
  },
 }
```
Using this configuration in JS API leads to generation of following icons:
![image](https://github.com/itgalaxy/favicons/assets/17229619/fcc448ac-0d65-4311-b61d-c6974a918729)
And all are the same size (expected to generate single icon 48x48). However, setting 
```ts
android: [
   'android-chrome-48x48.png',
],
``` works fine and produces only `android-chrome-48x48.png`.

**Comment by andy128k** [comment]
That's a confusing behavior but that's what happens when you maintains backward compatibility. :shrug: 

When an object is specified it is interpreted as an override to `every` icon from a default set. But when array is specified it overrides the set of icons to be generated.

Consider:

```js
android: { rotate: true }, // rotate every icon
```

and

```js
android: [
   'android-chrome-48x48.png', // 48x48 image is generated with default settings
   {
      name: 'android-chrome-72x72.png',
      rotate: true,
   },
],
```

Pay attention that file name is mandatory when you want to specify which sizes to generate.

**Comment by Yannik** [comment]
Thanks @andy128k!

Unfortunately, the documentation is not too clear about this, but your comment really helped me out!
